version: "3.8"
services:
  app:
    build: .
    volumes:
    - .:/django #describes a folder that resides on our OS within the container
    ports:
    - 8000:8000
    image: app:django
    container_name: django_rest_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
