# Generated by Django 3.1.7 on 2021-03-18 19:31

from django.db import migrations
import project_apps.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', project_apps.users.models.CustomUserManager()),
            ],
        ),
    ]
