# Generated by Django 3.1.7 on 2021-03-18 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=80)),
                ('diagnosis', models.CharField(max_length=30)),
                ('received_at', models.DateTimeField(auto_now=True)),
                ('signed_out', models.BooleanField(default=False)),
                ('room_number', models.CharField(max_length=5)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
